services:
    nextjs-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT}:3000'
        environment:
            - NODE_ENV=${NODE_ENV}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        env_file:
            - .env.local
        command: npm start
