services:
    politicians-front-end:
        container_name: politicians-front-end
        image: politicians-front-end
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT}:3000'
        environment:
            - NODE_ENV=${NODE_ENV}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        env_file:
            - .env
        command: npm start
        networks:
            - politicians_network

networks:
    politicians_network:
        driver: bridge
